name: bookswap_demo
description: A minimal BookSwap Flutter demo (mock data)
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.7+3
  lottie: ^2.4.0
  # Firebase packages (used when integrating backend)
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  uuid: ^4.5.2
  js: ^0.6.7
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png
    - ui/ui3.png
